#!/usr/bin/env python
#
#  The OpenDiamond Platform for Interactive Search
#  Version 5
#
#  Copyright (c) 2011 Carnegie Mellon University
#  All rights reserved.
#
#  This software is distributed under the terms of the Eclipse Public
#  License, Version 1.0 which can be found in the file named LICENSE.
#  ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS SOFTWARE CONSTITUTES
#  RECIPIENT'S ACCEPTANCE OF THIS AGREEMENT
#

import os
from opendiamond.bundle import bundle_python
from optparse import OptionParser
import sys

if __name__ == '__main__':
    parser = OptionParser(
        usage='%prog [-h] [-o outfile] [-b blob-path] filter-path',
        description='Package a Diamond filter written in Python into an OpenDiamond filter bundle.',
    )
    parser.add_option('-o', dest='outfile', metavar='outfile',
            help='path to output file')
    parser.add_option('-b', dest='blob', metavar='blob-path',
            help='path to optional data for blob argument')
    opts, args = parser.parse_args()
    if len(args) != 1:
        parser.error('no filter path specified')
    filter = args[0]
    outfile = opts.outfile
    if outfile is None:
        outfile = os.path.splitext(filter)[0] + '.zip'

    try:
        bundle_python(outfile, filter, opts.blob)
    except Exception, e:
        parser.error(str(e))
