#!/usr/bin/env python
#
#  The OpenDiamond Platform for Interactive Search
#  Version 5
#
#  Copyright (c) 2011 Carnegie Mellon University
#  All rights reserved.
#
#  This software is distributed under the terms of the Eclipse Public
#  License, Version 1.0 which can be found in the file named LICENSE.
#  ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS SOFTWARE CONSTITUTES
#  RECIPIENT'S ACCEPTANCE OF THIS AGREEMENT
#

from opendiamond.bundle import bundle_python
import sys

def usage():
    print "Usage: %s outfile filter-path [blob-path]" % sys.argv[0]
    sys.exit(1)

if __name__ == '__main__':
    try:
        args = sys.argv[1:]
        outfile = args.pop(0)
        if not outfile.endswith('.zip'):
            outfile += '.zip'
        filter = args.pop(0)
        try:
            blob = args.pop(0)
        except IndexError:
            blob = None
        if len(args) > 0:
            usage()
    except IndexError:
        usage()

    try:
        bundle_python(outfile, filter, blob)
    except Exception, e:
        print e, '\n'
        usage()
