/*
 *      Diamond (Release 1.0)
 *      A system for interactive brute-force search
 *
 *      Copyright (c) 2002-2005, Intel Corporation
 *      All Rights Reserved
 *
 *  This software is distributed under the terms of the Eclipse Public
 *  License, Version 1.0 which can be found in the file named LICENSE.
 *  ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS SOFTWARE CONSTITUTES
 *  RECIPIENT'S ACCEPTANCE OF THIS AGREEMENT
 */

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "od.h"


static char const cvsid[] =
    "$Header$";

void
messageprog_1(char *host)
{
	CLIENT         *clnt;
	int            *result_1;
	char           *printmessage_1_arg;
	int            *result_2;
	struct add_args add_gid_1_arg;

#ifndef	DEBUG

	clnt = clnt_create(host, MESSAGEPROG, MESSAGEVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
#endif				/* DEBUG */

	result_1 = printmessage_1(&printmessage_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror(clnt, "call failed");
	}
	result_2 = add_gid_1(&add_gid_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror(clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy(clnt);
#endif				/* DEBUG */
}


int
main(int argc, char *argv[])
{
	char           *host;

	if (argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	messageprog_1(host);
	exit(0);
}
