/*
 *
 *
 *                          Diamond 1.0
 * 
 *            Copyright (c) 2002-2004, Intel Corporation
 *                         All Rights Reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 * 
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above
 *      copyright notice, this list of conditions and the following
 *      disclaimer in the documentation and/or other materials provided
 *      with the distribution.
 *
 *    * Neither the name of Intel nor the names of its contributors may
 *      be used to endorse or promote products derived from this software 
 *      without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * rprintmsg.c: remote version of "printmsg.c"
 */


#include <stdio.h>
#include <rpc/rpc.h>     /* always needed  */
#include "od.h"         /* msg.h will be generated by rpcgen */

int
main(int argc, char **argv)
{
	CLIENT *        cl;
	int *           result;
	char *          server;
	char *          message;
	struct  update_gid_args    aa;
	groupid_t       gt;
	obj_id_t        oid;

	if (argc != 3) {
		fprintf(stderr, "usage: %s host message\n", argv[0]);
		exit(1);
	}

	server = argv[1];
	message = argv[2];


	/*
	 * Create client "handle" used for calling MESSAGEPROG on
	 * the server designated on the command line.  We tell
	 * the RPC package to use the TCP protocol when
	 * contacting the server.
	 */

	cl = clnt_create(server, MESSAGEPROG, MESSAGEVERS, "tcp");
	if (cl == NULL) {
		/* XXX no server */
		clnt_pcreateerror(server);
		exit(1);
	}

	gt = 1;
	aa.gid = &gt;
	aa.oid = &oid;

	result = rpc_add_gid_1(&aa, cl);
	if (result == NULL) {
		clnt_perror(cl, server);
		exit(1);
	}

	printf("after add: gid %llx \n", gt);


	if (*result == 0) {
		fprintf(stderr, "%s: %s couldn't print your message\n",
		        argv[0], server);
		exit(1);
	}
	printf("Message delivered to %s!\n", server);
	exit(0);
}


