image: docker:latest
services:
  - docker:dind

stages:
  - setup
  - build

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: "tcp://localhost:2375"

cache:
  paths:
    - .cache/
    - docker/miniconda.sh
    - docker/tini

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - mkdir -p .cache/apk && ln -sf `pwd`/.cache/apk /etc/apk/cache

setup_cache:
  stage: setup
  script:
    - apk update
    - apk add curl git tini-static
    - cp /sbin/tini-static docker/tini
    - curl https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh > docker/miniconda.sh

.docker_build_template: &docker_build
  stage: build
  script:
    - apk add git
    - git archive --output=docker/opendiamond-HEAD.tar.gz HEAD
    - docker pull $IMAGE_TAG:$DIST || true
    - docker build --pull --cache-from $IMAGE_TAG:$DIST -t $IMAGE_TAG:$DIST -f docker/Dockerfile.$DIST docker
    - docker push $IMAGE_TAG:$DIST

build_master.centos6:
  <<: *docker_build
  variables:
    DIST: centos6
    IMAGE_TAG: $CI_REGISTRY_IMAGE
  only:
    - master

build_other.centos6:
  <<: *docker_build
  variables:
    DIST: centos6
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME
  except:
    - master

build_master.centos7:
  <<: *docker_build
  variables:
    DIST: centos7
    IMAGE_TAG: $CI_REGISTRY_IMAGE
  only:
    - master

build_other.centos7:
  <<: *docker_build
  variables:
    DIST: centos7
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME
  except:
    - master

build_master.buster:
  <<: *docker_build
  variables:
    DIST: buster
    IMAGE_TAG: $CI_REGISTRY_IMAGE
  only:
    - master

build_other.buster:
  <<: *docker_build
  variables:
    DIST: buster
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME
  except:
    - master

build_master.xenial:
  <<: *docker_build
  variables:
    DIST: xenial
    IMAGE_TAG: $CI_REGISTRY_IMAGE
  only:
    - master

build_other.xenial:
  <<: *docker_build
  variables:
    DIST: xenial
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME
  except:
    - master
