image: docker:18.09.8
services:
  - docker:18.09.8-dind

stages:
  - build

cache:
  paths:
    - .cache/

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - mkdir -p .cache/apk && ln -sf `pwd`/.cache/apk /etc/apk/cache

setup_cache:
  stage: .pre
  script:
    - apk update
    - apk add git

.docker_build_template: &docker_build
  stage: build
  script:
    - apk add git
    - git archive --output=docker/opendiamond-HEAD.tar.gz HEAD
    - docker pull $IMAGE_TAG:$DIST || true
    - docker build --cache-from $IMAGE_TAG:$DIST --build-arg PIP_INDEX_URL --build-arg PIP_TRUSTED_HOST -t $IMAGE_TAG:$DIST -f docker/Dockerfile.$DIST docker
    - docker push $IMAGE_TAG:$DIST
  cache:
    policy: pull

build_master.centos6:
  <<: *docker_build
  variables:
    DIST: centos6
    IMAGE_TAG: $CI_REGISTRY_IMAGE
  only:
    - master

build_other.centos6:
  <<: *docker_build
  variables:
    DIST: centos6
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME
  except:
    - master

build_master.centos7:
  <<: *docker_build
  variables:
    DIST: centos7
    IMAGE_TAG: $CI_REGISTRY_IMAGE
  only:
    - master

build_other.centos7:
  <<: *docker_build
  variables:
    DIST: centos7
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME
  except:
    - master

build_master.buster:
  <<: *docker_build
  variables:
    DIST: buster
    IMAGE_TAG: $CI_REGISTRY_IMAGE
  only:
    - master

build_other.buster:
  <<: *docker_build
  variables:
    DIST: buster
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME
  except:
    - master

build_master.xenial:
  <<: *docker_build
  variables:
    DIST: xenial
    IMAGE_TAG: $CI_REGISTRY_IMAGE
  only:
    - master

build_other.xenial:
  <<: *docker_build
  variables:
    DIST: xenial
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME
  except:
    - master
