/* AUTOGENERATED FILE -- DO NOT EDIT */

/**
 * @file
 * @brief Data structures for the example protocol
 *
 * This header file contains the C equivalents of the data structures defined
 * in the @c .mx protocol definition file.  See the source code of
 * example_xdr.h for details.
 */

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef EXAMPLE_XDR_H
#define EXAMPLE_XDR_H

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

/**
 * @cond DISABLED
 */
enum example_color {
	RED = 0,
	ORANGE = 1,
	YELLOW = 2,
	GREEN = 3,
	BLUE = 4,
	INDIGO = 5,
	VIOLET = 6,
};
typedef enum example_color example_color;

struct example_color_choice {
	struct {
		u_int acceptable_len;
		enum example_color *acceptable_val;
	} acceptable;
	enum example_color preferred;
};
typedef struct example_color_choice example_color_choice;

typedef int example_count;


/* The xdr functions.  The application should never need to call these
   directly. */
#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_example_color (XDR *, example_color*);
extern  bool_t xdr_example_color_choice (XDR *, example_color_choice*);
extern  bool_t xdr_example_count (XDR *, example_count*);

#else /* K&R C */
extern bool_t xdr_example_color ();
extern bool_t xdr_example_color_choice ();
extern bool_t xdr_example_count ();

#endif /* K&R C */
/**
 * @endcond
 */

#ifdef __cplusplus
}
#endif

#endif /* !EXAMPLE_XDR_H */

/**
 * @}
 */
