# This file is generated by configure.
__version__ = '10.1.1'

PROJECT_NAME = 'opendiamond'
PROJECT_EMAIL = 'diamond@cs.cmu.edu'
PROJECT_URL = 'http://diamond.cs.cmu.edu/'

PROJECT_DESCRIPTION = "OpenDiamond Platform for Interactive Search"
PROJECT_AUTHOR = "Carnegie Mellon University"
PROJECT_LICENSE = "Eclipse Public License, Version 1.0"
