#!/bin/sh
#
#  The OpenDiamond Platform for Interactive Search
#
#  Copyright (c) 2007-2009 Carnegie Mellon University
#  All rights reserved.
#
#  This software is distributed under the terms of the Eclipse Public
#  License, Version 1.0 which can be found in the file named LICENSE.
#  ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS SOFTWARE CONSTITUTES
#  RECIPIENT'S ACCEPTANCE OF THIS AGREEMENT
#
#
#
#  This script is executed by a web browser when the gatekeeper sends
#  a new scope definition file.  Its current function is to place the
#  scope file into ~/.diamond/ for libscope to read and parse.
#

# Ensure ~/.diamond exists
mkdir -p $HOME/.diamond

# Concatenate the scope files as NEWSCOPE
cat "$@" /dev/null > $HOME/.diamond/NEWSCOPE

# Set permissions
chmod 600 $HOME/.diamond/NEWSCOPE

