#!/usr/bin/python
#
#  The OpenDiamond Platform for Interactive Search
#  Version 4
#
#  Copyright (c) 2009 Carnegie Mellon University
#  All rights reserved.
#
#  This software is distributed under the terms of the Eclipse Public
#  License, Version 1.0 which can be found in the file named LICENSE.
#  ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS SOFTWARE CONSTITUTES
#  RECIPIENT'S ACCEPTANCE OF THIS AGREEMENT
#

import logging
import optparse
from paste import httpserver

import opendiamond

server_version = "DataRetriever/" + opendiamond.__version__

parser = optparse.OptionParser()
parser.add_option("-l", "--listen", dest="host", default="127.0.0.1",
		  help="Bind with the specified listen address")
parser.add_option("-p", "--port",   dest="port", default="5873")
parser.add_option("-d", "--daemonize", dest="daemonize", action="store_true",
		  default=False)
(options, args) = parser.parse_args()

# Initialize logging
logging.getLogger().addHandler(logging.StreamHandler())

from opendiamond.helpers import daemonize
from dataretriever.util import DataRetriever
from dataretriever import diamond_store, proxy_store
#from dataretriever import mirage_store, flickr_store

app = DataRetriever({
    'collection':	diamond_store.scope_app,
    'proxy':		proxy_store.scope_app,
#    'mirage':		mirage_store.scope_app,
#    'flickr':		flickr_store.scope_app,
})

def run():
    if options.daemonize: daemonize()
    httpserver.serve(app, host=options.host, port=options.port,
                     server_version=server_version,
                     protocol_version='HTTP/1.1',
                     daemon_threads=True)

if __name__ == '__main__':
    run()
