#!/usr/bin/python
#
#  The OpenDiamond Platform for Interactive Search
#  Version 4
#
#  Copyright (c) 2009 Carnegie Mellon University
#  All rights reserved.
#
#  This software is distributed under the terms of the Eclipse Public
#  License, Version 1.0 which can be found in the file named LICENSE.
#  ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS SOFTWARE CONSTITUTES
#  RECIPIENT'S ACCEPTANCE OF THIS AGREEMENT
#

import logging
import optparse
from paste import httpserver

import opendiamond
from opendiamond.config import DiamondConfig
from opendiamond.helpers import daemonize
from dataretriever.util import DataRetriever
from dataretriever import diamond_store, proxy_store
#from dataretriever import mirage_store, flickr_store

server_version = "DataRetriever/" + opendiamond.__version__

parser = optparse.OptionParser()
parser.add_option("-f", "--config-file", dest="path")
parser.add_option("-l", "--listen", dest="retriever_host",
		  help="Bind with the specified listen address")
parser.add_option("-p", "--port", dest="retriever_port")
parser.add_option("-d", "--daemonize", dest="daemonize", action="store_true",
		  default=False)
(options, args) = parser.parse_args()

# Load config
kwargs = {}
for opt in 'path', 'retriever_host', 'retriever_port':
    if getattr(options, opt) is not None:
	kwargs[opt] = getattr(options, opt)
config = DiamondConfig(**kwargs)

# Initialize logging
logging.getLogger().addHandler(logging.StreamHandler())

app = DataRetriever({
    'collection':	diamond_store.scope_app,
    'proxy':		proxy_store.scope_app,
#    'mirage':		mirage_store.scope_app,
#    'flickr':		flickr_store.scope_app,
})

def run():
    if options.daemonize: daemonize()
    httpserver.serve(app, host=config.retriever_host,
                     port=config.retriever_port,
                     server_version=server_version,
                     protocol_version='HTTP/1.1',
                     daemon_threads=True)

if __name__ == '__main__':
    run()
