#!/usr/bin/env python
#
#  The OpenDiamond Platform for Interactive Search
#
#  Copyright (c) 2011 Carnegie Mellon University
#  All rights reserved.
#
#  This software is distributed under the terms of the Eclipse Public
#  License, Version 1.0 which can be found in the file named LICENSE.
#  ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS SOFTWARE CONSTITUTES
#  RECIPIENT'S ACCEPTANCE OF THIS AGREEMENT
#

import os
from opendiamond.bundle import bundle_generic, parse_manifest, BUNDLE_NS_PFX
from optparse import OptionParser

if __name__ == '__main__':
    parser = OptionParser(
        usage='%prog [-h] [-o outfile] manifest files...',
        description='Package an OpenDiamond predicate or codec.',
    )
    parser.add_option('-o', dest='outfile', metavar='outfile',
            help='path to output file')
    opts, args = parser.parse_args()
    if len(args) < 1:
        parser.error('no manifest specified')

    try:
        manifest = args.pop(0)
        element = parse_manifest(open(manifest).read())
        if element.tag == BUNDLE_NS_PFX + 'predicate':
            suffix = '.pred'
        elif element.tag == BUNDLE_NS_PFX + 'codec':
            suffix = '.codec'
        else:
            raise Exception('Unknown root element ' + element.tag)

        outfile = opts.outfile
        if outfile is None:
            outfile = os.path.splitext(manifest)[0] + suffix
        filemap = dict((os.path.basename(a), a) for a in args)

        bundle_generic(outfile, element, filemap)
    except Exception, e:
        parser.error(str(e))
