#!/usr/bin/env python
#
#  The OpenDiamond Platform for Interactive Search
#  Version 6
#
#  Copyright (c) 2011 Carnegie Mellon University
#  All rights reserved.
#
#  This software is distributed under the terms of the Eclipse Public
#  License, Version 1.0 which can be found in the file named LICENSE.
#  ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS SOFTWARE CONSTITUTES
#  RECIPIENT'S ACCEPTANCE OF THIS AGREEMENT
#

import os
from opendiamond.bundle import bundle_python
from optparse import OptionParser

if __name__ == '__main__':
    parser = OptionParser(
        usage='%prog [-h] [-o outfile] python-search [file...]',
        description='Package an OpenDiamond search written in Python into a search bundle.',
    )
    parser.add_option('-o', dest='outfile', metavar='outfile',
            help='path to output file')
    opts, args = parser.parse_args()
    if len(args) < 1:
        parser.error('no search path specified')
    search = args.pop(0)
    outfile = opts.outfile
    if outfile is None:
        outfile = os.path.splitext(search)[0] + '.search'

    try:
        bundle_python(outfile, search, args)
    except Exception, e:
        parser.error(str(e))
